<?php

namespace app\models\medis;

use Yii;
use app\models\pegawai\TbPegawai;
use app\models\pendaftaran\Layanan;

class AsesmenHemodialisaDokter extends BaseModelAR
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'medis.asesmen_hemodialisa_dokter';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['layanan_id', 'perawat_id'], 'required'],
            [['layanan_id', 'perawat_id', 'batal', 'draf', 'created_by', 'updated_by', 'is_deleted'], 'default', 'value' => null],
            [['layanan_id', 'perawat_id', 'batal', 'draf', 'created_by', 'updated_by', 'is_deleted','id_dokumen_rme'], 'integer'],
            [['tanggal_batal', 'tanggal_final', 'created_at', 'updated_at', 'tanggal_asesmen'], 'safe'],
            [['log_data', 'diagnosis_ginjal', 'etiologi', 'penyulit', 'penyakit_penyerta', 'anamnesis', 'pemeriksaan_fisik', 'pengkajian_fisik_ulang', 'hbs_ag', 'ureum', 'natrium', 'fe_serum', 'anti_hcv', 'kreatinin', 'kalsium', 'tibc', 'anti_hiv', 'asam_urat', 'poforanorganik', 'sa_transferin', 'hemoglobin', 'kalium', 'gula_darah','penunjang_lainnya', 'target_pengobatan', 'frekuensi_hd', 'pencapaian_adekuasi_dialisis', 'lainnya', 'akses_sirkulasi', 'durasi_hd', 'uf_goal', 'bb_kering', 'kecepatan_aliran_darah', 'kecepatan_aliran_dialisat', 'heparinisasi', 'program_profilling', 'suhu', 'terapi', 'perubahan_terapi', 'cara_bayar','versi','asal_pasien','dialisat','riwayat_alergi_obat','posisi_sirkulasi'], 'string'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'layanan_id' => 'Layanan ID',
            'perawat_id' => 'Perawat ID',
            'batal' => 'Batal',
            'tanggal_batal' => 'Tanggal Batal',
            'draf' => 'Draf',
            'tanggal_final' => 'Tanggal Final',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'log_data' => 'Log Data',
            'is_deleted' => 'Is Deleted',
            'diagnosis_ginjal' => 'Diagnosis Ginjal',
            'etiologi' => 'Etiologi',
            'penyulit' => 'Penyulit',
            'penyakit_penyerta' => 'Penyakit Penyerta',
            'anamnesis' => 'Anamnesis',
            'pemeriksaan_fisik' => 'Pemeriksaan Fisik',
            'pengkajian_fisik_ulang' => 'Pengkajian Fisik Ulang',
            'hbs_ag' => 'Hbs Ag',
            'ureum' => 'Ureum',
            'natrium' => 'Natrium',
            'fe_serum' => 'Fe Serum',
            'anti_hcv' => 'Anti Hcv',
            'kreatinin' => 'Kreatinin',
            'kalsium' => 'Kalsium',
            'tibc' => 'Tibc',
            'anti_hiv' => 'Anti Hiv',
            'asam_urat' => 'Asam Urat',
            'poforanorganik' => 'Poforanorganik',
            'sa_transferin' => 'Sa Transferin',
            'hemoglobin' => 'Hemoglobin',
            'kalium' => 'Kalium',
            'gula_darah' => 'Gula Darah',
            'penunjang_lainnya' => 'Penunjang Lainnya',
            'target_pengobatan' => 'Target Pengobatan',
            'frekuensi_hd' => 'Frekuensi Hd',
            'pencapaian_adekuasi_dialisis' => 'Pencapaian Adekuasi Dialisis',
            'lainnya' => 'Lainnya',
            'dialisat' => 'Dialisat',
            'akses_sirkulasi' => 'Akses Sirkulasi',
            'durasi_hd' => 'Durasi Hd',
            'uf_goal' => 'Uf Goal',
            'bb_kering' => 'Bb Kering',
            'kecepatan_aliran_darah' => 'Kecepatan Aliran Darah',
            'kecepatan_aliran_dialisat' => 'Kecepatan Aliran Dialisat',
            'heparinisasi' => 'Heparinisasi',
            'program_profilling' => 'Program Profilling',
            'suhu' => 'Suhu',
            'terapi' => 'Terapi',
            'perubahan_terapi' => 'Perubahan Terapi',
            'asal_pasien' => 'Asal Pasien',
            'riwayat_alergi_obat' => 'Riwayat Alergi Obat',
            'posisi_sirkulasi' => 'Posisi Sirkulasi',
            
        ];
    }

    public function beforeSave($insert) {
        if ($insert) {
            $this->batal = 0;
            $this->draf = 1;
            $this->is_deleted = 0;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function afterFind()
    {
        // parent::afterFind();
        
        $this->tanggal_asesmen =  Yii::$app->formatter->asDate($this->tanggal_asesmen, 'dd-MM-yyyy');
    }
    public static function find()
    {
        return new AsesmenHemodialisaDokterQuery(get_called_class());
    }
    public function getPerawat()
    {
        return $this->hasOne(TbPegawai::className(),['pegawai_id'=>'perawat_id']);
    }
    public function getLayanan()
    {
        return $this->hasOne(Layanan::className(),['id'=>'layanan_id']);
    }

}
