<?php

namespace app\models\medis;

use Yii;
use app\models\pegawai\TbPegawai;
use app\models\pendaftaran\Layanan;

class AsesmenHemodialisaDetail extends BaseModelAR
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'medis.asesmen_hemodialisa_awal_detail';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['asesmen_awal_id', 'perawat_id'], 'required'],
            [['asesmen_awal_id', 'perawat_id', 'created_by', 'updated_by'], 'default', 'value' => null],
            [['asesmen_awal_id', 'perawat_id', 'created_by', 'updated_by', 'updated_by','is_deleted','deleted_by'], 'integer'],
            [['observasi', 'jam', 'keterangan_lain', 'log_data', 'tek_darah'], 'string'],
            [['created_at', 'updated_at', 'deleted_at','komplikasi_hd','tanggal_implementasi'], 'safe'],
            [['qb', 'uf_rate', 'suhu', 'resp', 'intake_nacl', 'intake_dextro', 'intake_makan', 'intake_lain', 'output_uf_volume', 'nadi', 'qd', 'ktv_current'], 'number'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_asesmen_awl' => 'ID',
            'asesmen_awal_id' => 'Asesmen Awal ID',
            'perawat_id' => 'Perawat ID',
            'observasi' => 'Observasi',
            'jam' => 'Jam',
            'qb' => 'Qb Ml',
            'uf_rate' => 'Uf Rate',
            'tek_darah' => 'Tek Darah',
            'suhu' => 'Suhu',
            'resp' => 'Resp',
            'intake_nacl' => 'Intake Nacl',
            'intake_dextro' => 'Intake Dextro',
            'intake_makan' => 'Intake Makan',
            'intake_lain' => 'Intake Lain',
            'qd' => 'QD',
            'ktv_current' => 'Kt/V Current',
            'output_uf_volume' => 'Output Uf Volume',
            'keterangan_lain' => 'Keterangan Lain',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'log_data' => 'Log Data',
            'nadi' => 'Nadi',
            'komplikasi_hd' => 'Komplikasi HD',
            'is_deleted' => 'Is Deleted',
            'tanggal_implementasi' => 'Tanggal Implementasi'
        ];
    }

    public function beforeSave($insert) {
        if (parent::beforeSave($insert)) {
            if (is_array($this->komplikasi_hd)) {
                $this->komplikasi_hd = implode(',', $this->komplikasi_hd);
            }
            
            return true;
        } else {
            return false;
        }

        if ($insert) {
            $this->is_deleted = 0;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        parent::afterFind();
        if (is_string($this->komplikasi_hd)) {
            $this->komplikasi_hd = explode(',', $this->komplikasi_hd);
        }
    }

    public static function find()
    {
        return new AsesmenHemodialisaDetailQuery(get_called_class());
    }
    public function getPetugas()
    {
        return $this->hasOne(TbPegawai::className(),['pegawai_id'=>'perawat_id']);
    }
    public function getAsesmenAwal()
    {
        return $this->hasOne(AsesmenHemodialisa::className(),['id'=>'asesmen_awal_id']);
    }

}




