<?php

namespace app\models\medis;

use Yii;
use app\models\pegawai\TbPegawai;
use app\models\pendaftaran\Layanan;

class CatatanRehabMedik extends BaseModelAR
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'medis.catatan_rehab_medik';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['penjadwalan_rehab_medik_detail_id'], 'required'],
            [['penjadwalan_rehab_medik_detail_id', 'perawat_id', 'perawat_final', 'perawat_batal', 'batal', 'draf', 'created_by', 'updated_by', 'is_deleted'], 'default', 'value' => null],
            [[ 'layanan_id','perawat_id', 'perawat_final', 'perawat_batal','batal', 'draf', 'created_by', 'updated_by', 'is_deleted'], 'integer'],
            [['tanggal_batal', 'tanggal_final', 'created_at', 'updated_at','tgl_pelaksanaan'], 'safe'],
            [['log_data','tindakan_rs','catatan'], 'string'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'perawat_id' => 'Perawat ID',
            'layanan_id' => 'Layanan ID',
            'perawat_final' => 'Perawat Final',
            'perawat_batal' => 'Perawat Batal',
            'batal' => 'Batal',
            'tanggal_batal' => 'Tanggal Batal',
            'draf' => 'Draf',
            'tanggal_final' => 'Tanggal Final',
            'tgl_pelaksanaan' => 'Tanggal Pelaksanaan',
            'created_at' => 'Dibuat Pada',
            'created_by' => 'Dibuat Oleh',
            'updated_at' => 'Diperbarui Pada',
            'updated_by' => 'Diperbarui Oleh',
            'log_data' => 'Log Data',
            'is_deleted' => 'Dihapus',
            'tindakan_rs' => 'Tindakan RS',
            'catatan' => 'Catatan',
        ];
    }

    public function beforeSave($insert) {
        
        if ($insert) {
            $this->batal = 0;
            $this->draf = 1;
            $this->is_deleted = 0;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public static function find()
    {
        return new CatatanRehabMedikQuery(get_called_class());
    }
    public function getPerawat()
    {
        return $this->hasOne(TbPegawai::className(),['pegawai_id'=>'perawat_id']);
    }
    public function getPerawatFinal()
    {
        return $this->hasOne(TbPegawai::className(),['pegawai_id'=>'perawat_final']);
    }
    public function getPenjadwalanRehabMedikDetail()
    {
        return $this->hasOne(PenjadwalanRehabMedikDetail::className(), ['id_penjadwalan_rehab_medik_detail' => 'penjadwalan_rehab_medik_detail_id']);
                    // ->andWhere(['batal' => 0, 'draf' => 0]);
    }

    public function getLayanan()
    {
        return $this->hasOne(Layanan::className(),['id'=>'layanan_id']);
    }
    

}




