<?php

namespace app\models\medis;

use Yii;
use app\models\pegawai\TbPegawai;
use app\models\pendaftaran\Layanan;
/**
 * This is the model class for table "medis.diet_pasien".
 *
 * @property int $id
 * @property int $layanan_id reff pendaftaran.layanan.id
 * @property int $perawat_id reff pegawai.tb_pegawai.pegawai_id => id perawat isi
 * @property string $tanggal
 * @property string $jenis_diet MC=>Makanan Cairan|ML=>Makanan Lunak|MB=>Makanan Biasa
 * @property string|null $catatan_diet
 * @property int $batal
 * @property string|null $tanggal_batal
 * @property string $created_at
 * @property int $created_by
 * @property string|null $updated_at
 * @property int|null $updated_by
 * @property string|null $log_data
 * @property int $is_deleted
 */
class DietPasien extends BaseModelAR
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'medis.diet_pasien';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['layanan_id', 'perawat_id', 'jenis_diet'], 'required'],
            [['layanan_id', 'perawat_id', 'batal', 'created_by', 'updated_by', 'is_deleted'], 'default', 'value' => null],
            [['layanan_id', 'perawat_id', 'batal', 'created_by', 'updated_by', 'is_deleted'], 'integer'],
            [['tanggal', 'tanggal_batal', 'created_at', 'updated_at'], 'safe'],
            [['catatan_diet', 'log_data'], 'string'],
            [['jenis_diet'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'layanan_id' => 'Layanan',
            'perawat_id' => 'Perawat',
            'tanggal' => 'Tanggal',
            'jenis_diet' => 'Jenis Diet',
            'catatan_diet' => 'Catatan Diet',
            'batal' => 'Batal',
            'tanggal_batal' => 'Tanggal Batal',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'log_data' => 'Log Data',
            'is_deleted' => 'Is Deleted',
        ];
    }
    public function beforeSave($insert) {
        if ($insert) {
            $this->is_deleted = 0;
            $this->batal = 0;
            $this->tanggal=date('Y-m-d H:i:s');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     * @return DietPasienQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new DietPasienQuery(get_called_class());
    }
    public function getPerawat()
    {
        return $this->hasOne(TbPegawai::className(),['pegawai_id'=>'perawat_id']);
    }
    public function getLayanan()
    {
        return $this->hasOne(Layanan::className(),['id'=>'layanan_id']);
    }
}
