<?php

namespace app\models\medis;

use Yii;
use app\models\pegawai\TbPegawai;
/**
 * This is the model class for table "medis.dpjpri".
 *
 * @property int $id
 * @property string $registrasi_kode reff pendaftaran.registrasi.no_daftar
 * @property int $pegawai_id reff pegawai.tb_pegawai.pegawai_id
 * @property int $utama
 * @property string $tanggal_mulai default pada saat tanggal di create
 * @property string|null $tanggal_akhir default null
 * @property string|null $keterangan
 * @property string $created_at
 * @property int $created_by
 * @property string|null $updated_at
 * @property int|null $updated_by
 * @property string|null $log_data
 * @property int|null $is_deleted
 */
class Dpjpri extends BaseModelAR
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'medis.dpjpri';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['registrasi_kode', 'pegawai_id', 'tanggal_mulai','utama'], 'required'],
            [['pegawai_id', 'utama', 'created_by', 'updated_by', 'is_deleted'], 'default', 'value' => null],
            [['pegawai_id', 'utama', 'created_by', 'updated_by', 'is_deleted'], 'integer'],
            [['tanggal_mulai', 'tanggal_akhir', 'created_at', 'updated_at'], 'safe'],
            [['keterangan', 'log_data'], 'string'],
            [['registrasi_kode'], 'string', 'max' => 10],
            [['registrasi_kode'], 'string', 'max' => 10],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'registrasi_kode' => 'Registrasi Kode',
            'pegawai_id' => 'Dokter',
            'utama' => 'Status',
            'tanggal_mulai' => 'Tanggal Mulai',
            'tanggal_akhir' => 'Tanggal Akhir',
            'keterangan' => 'Keterangan',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'log_data' => 'Log Data',
            'is_deleted' => 'Is Deleted',
        ];
    }
    public function beforeSave($insert) {
        if ($insert) {
            $this->is_deleted = 0;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     * @return DpjpriQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new DpjpriQuery(get_called_class());
    }
    function getDokter()
    {
        return $this->hasOne(TbPegawai::className(),['pegawai_id'=>'pegawai_id']);
    }
}
