<?php

namespace app\models\medis;

use Yii;
use app\models\pegawai\TbPegawai;
use app\models\pegawai\DmUnitPenempatan;

/**
 * This is the model class for table "medis.jadwal_dokter_klinik".
 *
 * @property int $id
 * @property int $unit_kode reff pegawai.dm_unit_penempatan.kode
 * @property int $pegawai_id reff pegawai.tb_pegawai.pegawai_id
 * @property string $tanggal
 * @property string $jam_mulai
 * @property string $jam_akhir
 * @property string|null $keterangan
 * @property int|null $status_datang default 1 : 0=>Tidak Hadir|1=>Hadir|2=>Digantikan
 * @property string|null $datang_tanggal default null, jika datang entry datetime datang
 * @property int|null $ganti_pegawai_id default null, jika diganti entry pegawai_id =>reff pegawai.tb_pegawai.pegawai_id
 * @property string $created_at
 * @property int $created_by
 * @property string|null $updated_at
 * @property int|null $updated_by
 * @property string|null $log_data
 * @property int|null $is_deleted
 */
class JadwalDokterKlinik extends BaseModelAR
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'medis.jadwal_dokter_klinik';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['unit_kode', 'pegawai_id', 'tanggal', 'jam_mulai', 'jam_akhir'], 'required'],
            [['unit_kode', 'pegawai_id', 'status_datang', 'ganti_pegawai_id', 'created_by', 'updated_by', 'is_deleted'], 'default', 'value' => null],
            [['unit_kode', 'pegawai_id', 'status_datang', 'ganti_pegawai_id', 'created_by', 'updated_by', 'is_deleted'], 'integer'],
            [['tanggal', 'jam_mulai', 'jam_akhir',  'created_at', 'updated_at'], 'safe'],
            [['keterangan', 'log_data'], 'string'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'unit_kode' => 'Unit',
            'pegawai_id' => 'Dokter',
            'tanggal' => 'Tanggal',
            'jam_mulai' => 'Jam Mulai',
            'jam_akhir' => 'Jam Akhir',
            'keterangan' => 'Keterangan',
            'status_datang' => 'Status',
            'ganti_pegawai_id' => 'Dokter Ganti',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'log_data' => 'Log Data',
            'is_deleted' => 'Is Deleted',
        ];
    }
    public function beforeSave($insert) {
        if ($insert) {
            $this->is_deleted = 0;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     * @return JadwalDokterKlinikQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new JadwalDokterKlinikQuery(get_called_class());
    }
    function getUnit()
    {
        return $this->hasOne(DmUnitPenempatan::className(),['kode'=>'unit_kode']);
    }
    function getDokter()
    {
        return $this->hasOne(TbPegawai::className(),['pegawai_id'=>'pegawai_id']);
    }
    function getDokterGanti()
    {
        return $this->hasOne(TbPegawai::className(),['pegawai_id'=>'ganti_pegawai_id']);
    }
}
