<?php

namespace app\models\medis;

use Yii;
use app\models\pegawai\TbPegawai;
use app\models\pendaftaran\Layanan;
/**
 * This is the model class for table "medis.jawaban_konsultasi".
 *
 * @property int $id
 * @property int $permintaan_konsultasi_id reff medis.permintaan_konsultasi.id
 * @property int|null $layanan_id_jawab reff pendaftaran.layanan.id
 * @property int|null $dokter_id_jawab reff pegawai.tb_pegawai.id
 * @property string|null $tanggal_jawab
 * @property string|null $jawab_s
 * @property string|null $jawab_o
 * @property string|null $jawab_a
 * @property string|null $jawab_p
 * @property int $draf
 * @property string|null $tanggal_final
 * @property int $batal
 * @property string|null $tanggal_batal
 * @property string $created_at
 * @property int $created_by
 * @property string|null $updated_at
 * @property int|null $updated_by
 * @property string|null $log_data
 * @property int $is_deleted
 */
class JawabanKonsultasi extends BaseModelAR
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'medis.jawaban_konsultasi';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['permintaan_konsultasi_id'], 'required'],
            [['permintaan_konsultasi_id', 'layanan_id_jawab', 'dokter_id_jawab', 'draf', 'batal', 'created_by', 'updated_by', 'is_deleted'], 'default', 'value' => null],
            [['permintaan_konsultasi_id', 'layanan_id_jawab', 'dokter_id_jawab', 'draf', 'batal', 'created_by', 'updated_by', 'is_deleted'], 'integer'],
            [['tanggal_jawab', 'tanggal_final', 'tanggal_batal', 'created_at', 'updated_at'], 'safe'],
            [['jawab_s', 'jawab_o', 'jawab_a', 'jawab_p', 'log_data'], 'string'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'permintaan_konsultasi_id' => 'Permintaan Konsultasi ID',
            'layanan_id_jawab' => 'Layanan Id Jawab',
            'dokter_id_jawab' => 'Dokter Id Jawab',
            'tanggal_jawab' => 'Tanggal Jawab',
            'jawab_s' => 'Jawab S',
            'jawab_o' => 'Jawab O',
            'jawab_a' => 'Jawab A',
            'jawab_p' => 'Jawab P',
            'draf' => 'Draf',
            'tanggal_final' => 'Tanggal Final',
            'batal' => 'Batal',
            'tanggal_batal' => 'Tanggal Batal',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'log_data' => 'Log Data',
            'is_deleted' => 'Is Deleted',
        ];
    }
    public function beforeSave($insert) {
        if ($insert) {
            $this->is_deleted = 0;
            $this->batal = 0;
            $this->tanggal_jawab = date('Y-m-d H:i:s');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     * @return JawabanKonsultasiQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new JawabanKonsultasiQuery(get_called_class());
    }
    public function getDokterJawab()
    {
        return $this->hasOne(TbPegawai::className(),['pegawai_id'=>'dokter_id_jawab']);
    }
    public function getLayananJawab()
    {
        return $this->hasOne(Layanan::className(),['id'=>'layanan_id_jawab']);
    }
}
