<?php

namespace app\models\medis;

use Yii;
use app\models\pegawai\TbPegawai;
use app\models\pendaftaran\Layanan;
use app\components\HelperSpesialClass;

class PenjadwalanRehabMedikDetail extends BaseModelAR
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'medis.penjadwalan_rehab_medik_detail';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['tgl_rencana','ppa_id'], 'required'],
            [['penjadwalan_rehab_medik_id', 'created_by', 'updated_by'], 'default', 'value' => null],
            [['penjadwalan_rehab_medik_id', 'created_by', 'updated_by', 'deleted_by','is_deleted'], 'integer'],
            [['log_data'], 'string'],
            [['created_at', 'updated_at', 'deleted_at', 'tgl_rencana'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_rehab_medik_detail' => 'ID',
            'penjadwalan_rehab_medik_id' => 'Penjadwalan Rehab Medik ID',
            'ppa_id' => 'PPA',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'is_deleted' => 'Is Deleted',
            'tgl_rencana' => 'Tanggal Rencana',
        ];
    }

    public function beforeSave($insert) {

        if ($insert) {
            $this->is_deleted = 0;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


    public static function find()
    {
        return new PenjadwalanRehabMedikDetailQuery(get_called_class());
    }
    public function getMasterPpa()
    {
        return $this->hasOne(MasterPpa::className(),['id'=>'ppa_id']);
    }
    public function getPenjadwalanRehabMedik()
    {
        return $this->hasOne(PenjadwalanRehabMedik::className(),['id'=>'penjadwalan_rehab_medik_id']);
    }
    public function getCatatanRehabMedik()
    {
        $user=HelperSpesialClass::getUserLogin();

        return $this->hasMany(CatatanRehabMedik::className(), ['penjadwalan_rehab_medik_detail_id' => 'id_penjadwalan_rehab_medik_detail'])
        // ->andWhere(['perawat_id' => $user['pegawai_id']])
        ->andWhere([CatatanRehabMedik::tableName().'.batal' => 0])
        ->orderBy([CatatanRehabMedik::tableName().'.tanggal_final' => SORT_ASC]);

    }
}




