<?php

namespace app\models\medis;

use Yii;
use app\models\pegawai\TbPegawai;
use app\models\pendaftaran\Layanan;
use app\models\medis\RehabMedikDetail;

class PenjadwalanRehabMedik extends BaseModelAR
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'medis.penjadwalan_rehab_medik';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['rehab_medik_id'], 'required'],
            [['rehab_medik_id', 'perawat_id', 'perawat_final', 'perawat_batal', 'batal', 'draf', 'created_by', 'updated_by', 'is_deleted'], 'default', 'value' => null],
            [['rehab_medik_id','ppa_id', 'perawat_id', 'perawat_final', 'perawat_batal','batal', 'draf', 'created_by', 'updated_by', 'is_deleted'], 'integer'],
            [['tanggal_batal', 'tanggal_final', 'created_at', 'updated_at','tgl_rencana'], 'safe'],
            [['log_data'], 'string'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'rehab_medik_id' => 'Rehab Medik ID',
            'perawat_id' => 'Perawat ID',
            'perawat_final' => 'Perawat Final',
            'perawat_batal' => 'Perawat Batal',
            'batal' => 'Batal',
            'tanggal_batal' => 'Tanggal Batal',
            'draf' => 'Draf',
            'tanggal_final' => 'Tanggal Final',
            'tgl_rencana' => 'Tanggal Rencana',
            'created_at' => 'Dibuat Pada',
            'created_by' => 'Dibuat Oleh',
            'updated_at' => 'Diperbarui Pada',
            'updated_by' => 'Diperbarui Oleh',
            'log_data' => 'Log Data',
            'is_deleted' => 'Dihapus',
        ];
    }

    public function beforeSave($insert) {
        
        if ($insert) {
            $this->batal = 0;
            $this->draf = 1;
            $this->is_deleted = 0;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public static function find()
    {
        return new PenjadwalanRehabMedikQuery(get_called_class());
    }
    public function getPerawat()
    {
        return $this->hasOne(TbPegawai::className(),['pegawai_id'=>'perawat_id']);
    }
    public function getPerawatFinal()
    {
        return $this->hasOne(TbPegawai::className(),['pegawai_id'=>'perawat_final']);
    }
    public function getRehabMedik()
    {
        return $this->hasOne(RehabMedik::className(),['id'=>'rehab_medik_id']);
    }
    public function getPenjadwalanRehabMedikDetail()
    {
        return $this->hasMany(PenjadwalanRehabMedikDetail::className(),['penjadwalan_rehab_medik_id'=>'id']);
    }

    
    

}




