<?php

namespace app\models\medis;

use Yii;
use app\models\pegawai\TbPegawai;
use app\models\pendaftaran\Layanan;
/**
 * This is the model class for table "medis.pjp".
 *
 * @property int $id
 * @property int $layanan_id reff pendaftaran.layanan.id
 * @property int $pegawai_id reff pegawai.tb_pegawai.pegawai_id
 * @property int $dokter_utama default 0, jika 1 maka dokter utama
 * @property int $dokter_pendukung default 0, jika 1 maka dokter pendukung
 * @property int $perawat_utama default 0, jika 1 maka perawat utama
 * @property int $perawat_pendukung default 0, jika 1 maka perawat pendukung
 * @property string $tanggal_mulai RJ/RI default tanggal di daftarkan diruangan, jika RJ bisa kemungkinan pelayanan lebih satu hari maka add pjp dokter lagi
 * @property string|null $tanggal_akhir RJ/RI default null
 * @property string|null $keterangan
 * @property string $created_at
 * @property int $created_by
 * @property string|null $updated_at
 * @property int|null $updated_by
 * @property string|null $log_data
 * @property int $is_deleted
 */
class Pjp extends BaseModelAR
{
    const DPJP = 1;
    const DPJP_PENDUKUNG = 2;
    const PPJP = 3;
    const BPJP = 4;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'medis.pjp';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['layanan_id', 'pegawai_id', 'tanggal','status'], 'required'],
            [['layanan_id', 'pegawai_id', 'created_by', 'updated_by', 'is_deleted'], 'default', 'value' => null],
            [['layanan_id', 'pegawai_id', 'status', 'created_by', 'updated_by', 'is_deleted'], 'integer'],
            [['tanggal', 'created_at', 'updated_at'], 'safe'],
            [['keterangan', 'log_data'], 'string'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'layanan_id' => 'Layanan ID',
            'pegawai_id' => 'DPJP/PPJP',
            'status' => 'Status',
            'tanggal' => 'Tanggal',
            'keterangan' => 'Keterangan',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'log_data' => 'Log Data',
            'is_deleted' => 'Is Deleted',
        ];
    }
    public function beforeSave($insert) {
        if ($insert) {
            $this->is_deleted = 0;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     * @return PjpQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new PjpQuery(get_called_class());
    }
    function getPegawai()
    {
        return $this->hasOne(TbPegawai::className(),['pegawai_id'=>'pegawai_id']);
    }
    function getLayanan()
    {
        return $this->hasOne(Layanan::className(),['id'=>'layanan_id']);
    }
}
