<?php

namespace app\models\medis;

use Yii;
use app\models\pegawai\TbPegawai;
use app\models\pendaftaran\Registrasi;
/**
 * This is the model class for table "medis.pjp_ri".
 *
 * @property int $id
 * @property string $registrasi_kode reff pendaftaran.registrasi.kode
 * @property int $pegawai_id reff pegawai.tb_pegawai.pegawai_id
 * @property int $status default 0, jika 1 => dokter utama,2 => dokter pendukung, 3 => perawat
 * @property string $tanggal_mulai default input tanggal di daftarkan
 * @property string|null $tanggal_akhir default null
 * @property string|null $keterangan
 * @property string $created_at
 * @property int $created_by
 * @property string|null $updated_at
 * @property int|null $updated_by
 * @property string|null $log_data
 * @property int $is_deleted
 */
class PjpRi extends BaseModelAR
{
    const DPJP = 1;
    const DPJP_PENDUKUNG = 2;
    const PPJP = 3;
    const BPJP = 4;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'medis.pjp_ri';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['registrasi_kode', 'pegawai_id', 'tanggal_mulai','status'], 'required'],
            [['pegawai_id', 'status', 'created_by', 'updated_by', 'is_deleted'], 'default', 'value' => null],
            [['pegawai_id', 'status', 'created_by', 'updated_by', 'is_deleted'], 'integer'],
            [['tanggal_mulai', 'tanggal_akhir', 'created_at', 'updated_at'], 'safe'],
            [['keterangan', 'log_data'], 'string'],
            [['registrasi_kode'], 'string', 'max' => 10],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'registrasi_kode' => 'Registrasi Kode',
            'pegawai_id' => 'DPJP/PPJP',
            'status' => 'Status',
            'tanggal_mulai' => 'Tanggal Mulai',
            'tanggal_akhir' => 'Tanggal Akhir',
            'keterangan' => 'Keterangan',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'log_data' => 'Log Data',
            'is_deleted' => 'Is Deleted',
        ];
    }
    public function beforeSave($insert) {
        if ($insert) {
            $this->is_deleted = 0;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     * @return PjpRiQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new PjpRiQuery(get_called_class());
    }
    function getPegawai()
    {
        return $this->hasOne(TbPegawai::className(),['pegawai_id'=>'pegawai_id']);
    }
    function getRegistrasi()
    {
        return $this->hasOne(Registrasi::className(),['kode'=>'registrasi_kode']);
    }
}
