<?php

namespace app\models\medis;

use Yii;
use app\models\pegawai\TbPegawai;
use app\models\pendaftaran\Layanan;

class RehabMedikDetail extends BaseModelAR
{
    public $prosedurText;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'medis.asesmen_rehab_medik_detail';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['tindakan_id','hasil'], 'required'],
            [['rehab_medik_id', 'created_by', 'updated_by'], 'default', 'value' => null],
            [['rehab_medik_id', 'created_by', 'updated_by', 'deleted_by','is_deleted','tindakan_id'], 'integer'],
            [[ 'hasil','prosedur'], 'string'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_rehab_medik_detail' => 'ID',
            'rehab_medik_id' => 'Rehab Medik ID',
            'prosedur' => 'Prosedur',
            'hasil' => 'Hasil',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'is_deleted' => 'Is Deleted',
        ];
    }

    public function beforeSave($insert) {
        // if (parent::beforeSave($insert)) {
        //     if (is_array($this->komplikasi_hd)) {
        //         $this->komplikasi_hd = implode(',', $this->komplikasi_hd);
        //     }
            
        //     return true;
        // } else {
        //     return false;
        // }

        if ($insert) {
            $this->is_deleted = 0;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        // parent::afterFind();
        // if (is_string($this->komplikasi_hd)) {
        //     $this->komplikasi_hd = explode(',', $this->komplikasi_hd);
        // }
    }

    public static function find()
    {
        return new RehabMedikDetailQuery(get_called_class());
    }
    function getTindakan()
    {
        return $this->hasOne(Tindakan::className(),['id'=>'tindakan_id']);
    }

}




