<?php

namespace app\models\medis;

use Yii;
use app\models\pegawai\DmUnitPenempatan;
use app\components\HelperSpesialClass;
use app\models\pegawai\TbPegawai;
use app\models\pendaftaran\Layanan;
/**
 * This is the model class for table "medis.resep".
 *
 * @property int $id
 * @property string $no_transaksi generate by system trigger
 * @property int $depo_id unit depo for reff pegawai.dm_unit_penepatan.kode
 * @property string $tanggal
 * @property int $kronis
 * @property string $diagnosa
 * @property string|null $racikan_txt
 * @property string $created_at
 * @property int $created_by
 * @property string|null $updated_at
 * @property int|null $updated_by
 * @property int $is_deleted
 */
class Resep extends BaseModelAR
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'medis.resep';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['layanan_id','dokter_id', 'depo_id', 'diagnosa','kronis','racikan'], 'required'],
            [['layanan_id','dokter_id', 'depo_id', 'kronis', 'created_by', 'updated_by', 'is_deleted'], 'default', 'value' => null],
            [['layanan_id','dokter_id', 'depo_id', 'kronis', 'created_by', 'updated_by', 'is_deleted'], 'integer'],
            [['tanggal', 'created_at', 'updated_at'], 'safe'],
            [['diagnosa', 'racikan_txt','log_data'], 'string'],
            [['no_transaksi'], 'string', 'max' => 20],
            [['no_transaksi'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'layanan_id' => 'Layanan',
            'dokter_id'=>'Dokter',
            'no_transaksi' => 'No.Transaksi',
            'depo_id' => 'Depo',
            'tanggal' => 'Tanggal',
            'kronis' => 'Kronis',
            'racikan' => 'Racikan',
            'diagnosa' => 'Diagnosa',
            'racikan_txt' => 'Racikan',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'log_data' => 'Log Data',
            'is_deleted' => 'Is Deleted',
        ];
    }
    // public function beforeSave($insert)
    // {
    //     if($insert){
    //         $this->created_at   = date('Y-m-d H:i:s');
    //         $this->created_by = HelperSpesialClass::getUserLogin();
    //         $this->is_deleted=0;
    //     }else{
    //         $this->updated_at   = date('Y-m-d H:i:s');
    //         $this->updated_by = HelperSpesialClass::getUserLogin();
    //     }
    //     return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    // }
    public function beforeSave($insert) {
        if ($insert) {
            $this->is_deleted = 0;
            $this->tanggal=date('Y-m-d H:i:s');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     * @return ResepQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ResepQuery(get_called_class());
    }
    public function getResepDetail()
    {
        return $this->hasMany(ResepDetail::className(), ['resep_id' => 'id']);
    }
    public function getDepo()
    {
        return $this->hasOne(DmUnitPenempatan::className(),['kode'=>'depo_id']);
    }
    public function getDokter()
    {
        return $this->hasOne(TbPegawai::className(),['pegawai_id'=>'dokter_id']);
    }
    public function getLayanan()
    {
        return $this->hasOne(Layanan::className(),['id'=>'layanan_id']);
    }
}
