<?php

namespace app\models\medis;

use Yii;
use app\models\pegawai\TbPegawai;
use app\models\pendaftaran\Layanan;

class RingkasanPulangIgd extends BaseModelAR
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'medis.ringkasan_pulang_igd';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
             [['layanan_id', 'dokter_id'], 'required'],
            [['layanan_id', 'dokter_id', 'batal', 'draf', 'created_by', 'updated_by', 'is_deleted'], 'default', 'value' => null],
            [['layanan_id', 'dokter_id', 'batal', 'draf', 'created_by', 'updated_by', 'is_deleted'], 'integer'],
            [['tgl_datang', 'tgl_keluar', 'tanggal_batal', 'tanggal_final', 'created_at', 'updated_at'], 'safe'],
            [['indikasi_masuk', 'keluhan_utama', 'pemeriksaan_fisik', 'pemeriksaan_penunjang', 'diagnosa_kerja', 'diagnosa_banding', 'tindakan', 'tindak_lanjut_paps', 'tindak_lanjut_pap', 'tindak_lanjut_kontrol', 'tindak_lanjut_dirujuk', 'tindak_lanjut_meninggal_wib', 'alasan_tidak_dirawat_ku', 'alasan_tidak_dirawat_tk', 'alasan_tidak_dirawat_lainya', 'terapi_tindakan_diberikan', 'kondisi_keluar_ku', 'kondisi_keluar_kesadaran', 'kondisi_keluar_vs_td_mmhg', 'kondisi_keluar_vs_nadi_xm', 'kondisi_keluar_vs_rr_xm', 'kondisi_keluar_vs_suhu_c', 'kondisi_keluar_vs_nyeri', 'kondisi_keluar_terapi_pulang', 'edukasi_bisa', 'edukasi_kepada', 'saran', 'log_data'], 'string'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'layanan_id' => 'Layanan ID',
            'dokter_id' => 'Dokter ID',
            'tgl_datang' => 'Tgl Datang',
            'tgl_keluar' => 'Tgl Keluar',
            'indikasi_masuk' => 'Indikasi Masuk',
            'keluhan_utama' => 'Keluhan Utama',
            'pemeriksaan_fisik' => 'Pemeriksaan Fisik',
            'pemeriksaan_penunjang' => 'Pemeriksaan Penunjang',
            'diagnosa_kerja' => 'Diagnosa Kerja',
            'diagnosa_banding' => 'Diagnosa Banding',
            'tindakan' => 'Tindakan',
            'tindak_lanjut_paps' => 'Tindak Lanjut Paps',
            'tindak_lanjut_pap' => 'Tindak Lanjut Pap',
            'tindak_lanjut_kontrol' => 'Tindak Lanjut Kontrol',
            'tindak_lanjut_dirujuk' => 'Tindak Lanjut Dirujuk',
            'tindak_lanjut_meninggal_wib' => 'Tindak Lanjut Meninggal Wib',
            'alasan_tidak_dirawat_ku' => 'Alasan Tidak Dirawat Ku',
            'alasan_tidak_dirawat_tk' => 'Alasan Tidak Dirawat Tk',
            'alasan_tidak_dirawat_lainya' => 'Alasan Tidak Dirawat Lainya',
            'terapi_tindakan_diberikan' => 'Terapi Tindakan Diberikan',
            'kondisi_keluar_ku' => 'Kondisi Keluar Ku',
            'kondisi_keluar_kesadaran' => 'Kondisi Keluar Kesadaran',
            'kondisi_keluar_vs_td_mmhg' => 'Kondisi Keluar Vs Td Mmhg',
            'kondisi_keluar_vs_nadi_xm' => 'Kondisi Keluar Vs Nadi Xm',
            'kondisi_keluar_vs_rr_xm' => 'Kondisi Keluar Vs Rr Xm',
            'kondisi_keluar_vs_suhu_c' => 'Kondisi Keluar Vs Suhu C',
            'kondisi_keluar_vs_nyeri' => 'Kondisi Keluar Vs Nyeri',
            'kondisi_keluar_terapi_pulang' => 'Kondisi Keluar Terapi Pulang',
			'edukasi_bisa' => 'Pasien Bisa Diedukasi (y/tdk alasan)',
			'edukasi_kepada' => 'Kepada siapa pasien di edukasi',
            // 'edukasi_pasien' => 'Edukasi Pasien',
            // 'edukasi_keluarga_pasien' => 'Edukasi Keluarga Pasien',
            // 'edukasi_hub_pasien' => 'Edukasi Hub Pasien',
            // 'edukasi_tidak' => 'Edukasi Tidak',
            'saran' => 'Saran',
            'batal' => 'Batal',
            'tanggal_batal' => 'Tanggal Batal',
            'draf' => 'Draf',
            'tanggal_final' => 'Tanggal Final',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'log_data' => 'Log Data',
            'is_deleted' => 'Is Deleted',
        ];
    }
    public function beforeSave($insert) {
        if ($insert) {
            $this->is_deleted = 0;
            $this->batal = 0;
            $this->draf=1;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     * @return ResumeMedisRiQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new RingkasanPulangIgdQuery(get_called_class());
    }
    public function getDokter()
    {
        return $this->hasOne(TbPegawai::className(),['pegawai_id'=>'dokter_id']);
    }
    public function getLayanan()
    {
        return $this->hasOne(Layanan::className(),['id'=>'layanan_id']);
    }
}
